version: '3.8'
services:
  name: scraper
  scraper:
    build:
      context: https://github.com/TristanDBioC/zaneco-scraper.git#main:scraper
    env_file:
      - ./scraper/.env
    restart: always
    depends_on:
      - mongo

  mongo:
    name: scraper-mongodb
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: zaneco