services:
  scraper:
    container_name: scraper
    build:
      context: ./scraper
    env_file:
      - ./scraper/.env
    restart: always
    depends_on:
      - mongo
    volumes:
      - ./scraper:/app

  mongo:
    container_name: scraper-mongodb
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: zaneco
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: